CREATE TABLE JOBS(
    JOB_ID INTEGER PRIMARY KEY NOT NULL,
    JOB_NUMBER CHAR(250) UNIQUE NOT NULL
);

CREATE TABLE GENOMEMAP_INFO(
    ID INTEGER PRIMARY KEY NOT NULL,
    JOB_NUMBER CHAR(250) UNIQUE NOT NULL,
    DATUM BLOB NOT NULL,
    FOREIGN KEY (JOB_NUMBER) REFERENCES JOBS (JOB_NUMBER)
);